// Copyright 2021 Mozilla Foundation
// Licensed under the Apache License, Version 2.0.
// Ported from pdf.js/web/xfa_layer_builder.js and src/display/xfa_layer.js.

import 'dart:js_interop';

import 'package:pdfjs/pdfjs.dart';
import 'package:web/web.dart' as web;

import 'layer_page_adapter.dart';
import 'pdf_link_service.dart';

final class XfaRenderResult {
  const XfaRenderResult(this.textNodes);
  final List<web.Text> textNodes;
}

/// Renders the XFA HTML tree generated by the PDF worker.
final class XfaLayerRenderer {
  static XfaRenderResult render({
    required web.HTMLDivElement div,
    required Map<String, dynamic> xfaHtml,
    required PageViewport viewport,
    required PDFLinkService linkService,
    AnnotationStorage? annotationStorage,
    String intent = 'display',
  }) {
    final root = _createElement(xfaHtml);
    div.append(root);
    div.style.transform = 'matrix(${viewport.transform.join(',')})';
    if (intent != 'richText') div.className = 'xfaLayer xfaFont';
    _setAttributes(
      root,
      xfaHtml,
      linkService: linkService,
      storage: null,
      intent: intent,
    );

    final textNodes = <web.Text>[];
    _appendChildren(
      root,
      xfaHtml,
      textNodes,
      linkService: linkService,
      storage: annotationStorage,
      intent: intent,
    );
    final readOnly = div.querySelectorAll(
      '.xfaNonInteractive input, .xfaNonInteractive textarea',
    );
    for (var index = 0; index < readOnly.length; index++) {
      final element = readOnly.item(index);
      if (element is web.Element) element.setAttribute('readonly', '');
    }
    return XfaRenderResult(textNodes);
  }

  static void update(web.HTMLDivElement div, PageViewport viewport) {
    div.style.transform = 'matrix(${viewport.transform.join(',')})';
    div.removeAttribute('hidden');
  }

  static web.Element _createElement(Map<String, dynamic> node) {
    final name = node['name']?.toString() ?? 'div';
    final attributes = node['attributes'];
    final namespace =
        attributes is Map ? attributes['xmlns']?.toString() : null;
    return namespace == null
        ? web.document.createElement(name)
        : web.document.createElementNS(namespace, name);
  }

  static void _appendChildren(
    web.Element parent,
    Map<String, dynamic> node,
    List<web.Text> textNodes, {
    required PDFLinkService linkService,
    required AnnotationStorage? storage,
    required String intent,
  }) {
    final rawChildren = node['children'];
    if (rawChildren is List && rawChildren.isNotEmpty) {
      for (final raw in rawChildren) {
        if (raw is! Map) continue;
        final child = Map<String, dynamic>.from(raw);
        if (child['name'] == '#text') {
          final text =
              web.document.createTextNode(child['value']?.toString() ?? '');
          textNodes.add(text);
          parent.append(text);
          continue;
        }
        final element = _createElement(child);
        parent.append(element);
        _setAttributes(
          element,
          child,
          linkService: linkService,
          storage: storage,
          intent: intent,
        );
        _appendChildren(
          element,
          child,
          textNodes,
          linkService: linkService,
          storage: storage,
          intent: intent,
        );
      }
      return;
    }
    final value = node['value'];
    if (value != null) {
      final text = web.document.createTextNode(value.toString());
      if (intent != 'richText' && _shouldBuildText(node['name']?.toString())) {
        textNodes.add(text);
      }
      parent.append(text);
    }
  }

  static void _setAttributes(
    web.Element element,
    Map<String, dynamic> node, {
    required PDFLinkService linkService,
    required AnnotationStorage? storage,
    required String intent,
  }) {
    final raw = node['attributes'];
    if (raw is! Map) return;
    final attributes = Map<String, dynamic>.from(raw);
    if (attributes['type'] == 'radio' && attributes['name'] != null) {
      attributes['name'] = '${attributes['name']}-$intent';
    }
    for (final entry in attributes.entries) {
      final value = entry.value;
      if (value == null) continue;
      switch (entry.key) {
        case 'class':
          if (value is List) {
            if (value.isNotEmpty) element.className = value.join(' ');
          } else if (value.toString().isNotEmpty) {
            element.className = value.toString();
          }
        case 'dataId':
          break;
        case 'id':
          element.setAttribute('data-element-id', value.toString());
        case 'style':
          if (element is web.HTMLElement && value is Map) {
            for (final style in value.entries) {
              element.style
                  .setProperty(style.key.toString(), style.value.toString());
            }
          }
        case 'textContent':
          element.textContent = value.toString();
        case 'xmlns':
          break;
        default:
          if (element is! web.HTMLAnchorElement ||
              (entry.key != 'href' && entry.key != 'newWindow')) {
            element.setAttribute(entry.key, value.toString());
          }
      }
    }
    if (element is web.HTMLAnchorElement) {
      final href = attributes['href']?.toString() ?? '';
      if (href.isNotEmpty) {
        linkService.addLinkAttributes(
          HtmlAnchorElementAdapter(element),
          href,
          newWindow: attributes['newWindow'] == true,
        );
      }
    }
    final id = attributes['dataId']?.toString();
    if (storage != null && id != null) {
      _setupStorage(element, node, id, storage, intent);
    }
  }

  static void _setupStorage(
    web.Element element,
    Map<String, dynamic> node,
    String id,
    AnnotationStorage storage,
    String intent,
  ) {
    final attributes = Map<String, dynamic>.from(node['attributes'] as Map);
    final stored = storage.getValue(id, <String, dynamic>{'value': null});
    final storedValue = stored is Map ? stored['value'] : null;
    if (element is web.HTMLTextAreaElement) {
      if (storedValue != null) element.value = storedValue.toString();
      if (intent != 'print') {
        element.addEventListener(
            'input',
            ((web.Event _) {
              storage.setValue(id, {'value': element.value});
            }).toJS);
      }
    } else if (element is web.HTMLInputElement) {
      if (element.type == 'radio' || element.type == 'checkbox') {
        final on = attributes['xfaOn'];
        final off = attributes['xfaOff'];
        if (storedValue == on) {
          element.checked = true;
        } else if (storedValue == off) {
          element.checked = false;
        }
        if (intent != 'print') {
          element.addEventListener(
              'change',
              ((web.Event _) {
                storage.setValue(id, {'value': element.checked ? on : off});
              }).toJS);
        }
      } else {
        if (storedValue != null) element.value = storedValue.toString();
        if (intent != 'print') {
          element.addEventListener(
              'input',
              ((web.Event _) {
                storage.setValue(id, {'value': element.value});
              }).toJS);
        }
      }
    } else if (element is web.HTMLSelectElement) {
      if (storedValue != null) element.value = storedValue.toString();
      if (intent != 'print') {
        element.addEventListener(
            'input',
            ((web.Event _) {
              storage.setValue(id, {'value': element.value});
            }).toJS);
      }
    }
  }

  static bool _shouldBuildText(String? name) =>
      name != null &&
      !const {'input', 'textarea', 'select', 'option'}.contains(name);
}

/// Owns one XFA overlay and preserves PDF.js display/print semantics.
final class XfaLayerBuilder {
  XfaLayerBuilder({
    required this.pdfPage,
    required this.linkService,
    this.annotationStorage,
    this.xfaHtml,
  });

  final LayerPage pdfPage;
  final AnnotationStorage? annotationStorage;
  final PDFLinkService linkService;
  final Map<String, dynamic>? xfaHtml;
  web.HTMLDivElement? div;
  bool _cancelled = false;

  bool get cancelled => _cancelled;

  Future<XfaRenderResult> render({
    required PageViewport viewport,
    String intent = 'display',
  }) async {
    if (intent == 'print') {
      final container = web.document.createElement('div') as web.HTMLDivElement;
      div = container;
      final source = xfaHtml;
      if (source == null) return const XfaRenderResult([]);
      return XfaLayerRenderer.render(
        div: container,
        xfaHtml: source,
        viewport: viewport.clone(dontFlip: true),
        linkService: linkService,
        annotationStorage: annotationStorage,
        intent: intent,
      );
    }
    final source = await pdfPage.getXfa();
    if (_cancelled || source == null) return const XfaRenderResult([]);
    final current = div;
    if (current != null) {
      XfaLayerRenderer.update(current, viewport.clone(dontFlip: true));
      return const XfaRenderResult([]);
    }
    final container = web.document.createElement('div') as web.HTMLDivElement;
    div = container;
    return XfaLayerRenderer.render(
      div: container,
      xfaHtml: source,
      viewport: viewport.clone(dontFlip: true),
      linkService: linkService,
      annotationStorage: annotationStorage,
      intent: intent,
    );
  }

  void cancel() => _cancelled = true;

  void hide() => div?.setAttribute('hidden', '');
}
